--Oracle 
 
CREATE TABLE "MASTER_STOCK" 
   (	"STOCK_KEY" NUMBER, 
	"STOCK_SYMBOL" VARCHAR2(20 BYTE), 
	"UPDT_DTTM" DATE, 
	"STOCK_IND_KEY" NUMBER(*,0), 
	"MARKET_CAP" NUMBER
   )
   
     CREATE TABLE "YHOOFINDB"."STOCK_DAILY_HISTORY" 
   (	"STOCK_KEY" NUMBER, 
	"DT" DATE, 
	"UPDT_DTTM" DATE, 
	"DAY_OPEN" NUMBER, 
	"DAY_HIGH" NUMBER, 
	"DAY_LOW" NUMBER, 
	"DAY_CLOSE" NUMBER, 
	"VOLUME" NUMBER
   )
   
--Postgre
   CREATE TABLE "MASTER_STOCK" (
    "STOCK_KEY" serial PRIMARY KEY,
    "STOCK_SYMBOL" VARCHAR (50) UNIQUE NOT NULL,
    "UPDT_DTTM" TIMESTAMP,
    "MARKET_CAP" bigint,
    "STOCK_IND_KEY" integer
);

 CREATE TABLE "STOCK_DAILY_HISTORY" 
   (	"STOCK_KEY" INTEGER, 
	"DT" DATE, 
	"UPDT_DTTM" DATE, 
	"DAY_OPEN" INTEGER, 
	"DAY_HIGH" INTEGER, 
	"DAY_LOW" INTEGER, 
	"DAY_CLOSE" INTEGER, 
	"VOLUME" BIGINT
   )